### PR TITLE
Fix validate-spi-manifest tool usage text

### PR DESCRIPTION
**Pull request by Kyle-Ye**
```
swift run spi-manifest-validate ../swift-mmio/.spi.yml
// error: no executable product named 'spi-manifest-validate'
```

```
swift run validate-spi-manifest ../swift-mmio/.spi.yml
// ✅
```

### CODE REVIEW

**Comment by daveverwer** [comment]
Hi Kyle! Thanks for spotting this!

If you don't want to bother with a CLA for this small change then I can make the fix. But if you think it will be useful to set up a CLA now for other repositories across this org, then drop an email to the email address above and I'll get a template across for your signature.

**Comment by Kyle-Ye** [comment]
> then drop an email to the email address above and I'll get a template across for your signature.

Send the email address one but did not get a response yet.
image

**Comment by daveverwer** [comment]
@cla-bot recheck

**Comment by daveverwer** [comment]
@cla-bot check

**Review by daveverwer — APPROVED** [review]
Thanks @Kyle-Ye!

**Pull request merged**
